-- 코드를 입력하세요
SELECT B.AUTHOR_ID,B.AUTHOR_NAME,A.CATEGORY,SUM(C.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK A JOIN AUTHOR B JOIN BOOK_SALES C
ON A.BOOK_ID=C.BOOK_ID AND A.AUTHOR_ID=B.AUTHOR_ID
WHERE C.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY A.AUTHOR_ID,A.CATEGORY
ORDER BY 1, 3 DESC;
