-- 다시 한번 풀자 답 참고해서 풀었음!
# SELECT P.PRODUCT_CODE,P.PRICE*SUM(O.SALES_AMOUNT) AS SALES
# FROM PRODUCT P JOIN OFFLINE_SALE O
# ON P.PRODUCT_ID=O.PRODUCT_ID
# GROUP BY P.PRODUCT_ID
# ORDER BY P.PRICE*SUM(O.SALES_AMOUNT) DESC, P.PRODUCT_CODE;

SELECT A.PRODUCT_CODE, B.SOLD*A.PRICE AS SALES
FROM PRODUCT A JOIN (SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS SOLD
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY 2 DESC,1;