-- 다시 한번 풀자 답 참고해서 풀었음!
# SELECT P.PRODUCT_CODE,P.PRICE*SUM(O.SALES_AMOUNT) AS SALES
# FROM PRODUCT P JOIN OFFLINE_SALE O
# ON P.PRODUCT_ID=O.PRODUCT_ID
# GROUP BY P.PRODUCT_ID
# ORDER BY P.PRICE*SUM(O.SALES_AMOUNT) DESC, P.PRODUCT_CODE;

SELECT P.PRODUCT_CODE AS PRODUCT_CODE,P.PRICE*SUM(O.SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O
ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY 2 DESC,1;