-- 코드를 입력하세요
SELECT B.REST_ID,B.REST_NAME,B.FOOD_TYPE,B.FAVORITES,B.ADDRESS, ROUND(A.SCORE,2) AS SCORE
FROM (SELECT REST_ID,AVG(REVIEW_SCORE) SCORE FROM REST_REVIEW GROUP BY REST_ID) A 
JOIN REST_INFO B
ON A.REST_ID=B.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY 6 DESC, 4 DESC;