-- 코드를 입력하세요
SELECT PRODUCT_ID,PRODUCT_NAME,SUM(PRICE*AMOUNT)
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
USING (PRODUCT_ID)
WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
GROUP BY PRODUCT_ID
ORDER BY 3 DESC,1;