-- 코드를 입력하세요
SELECT HISTORY_ID,ROUND((DATEDIFF(END_DATE,START_DATE)+1)*A.DAILY_FEE*(100-IFNULL(C.DISCOUNT_RATE,0))/100) FEE
# SELECT A.CAR_ID,B.HISTORY_ID,START_DATE,END_DATE,DATEDIFF(END_DATE,START_DATE)+1,DISCOUNT_RATE,A.DAILY_FEE,ROUND((DATEDIFF(END_DATE,START_DATE)+1)*A.DAILY_FEE*(100-IFNULL(C.DISCOUNT_RATE,0))/100) FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON ((DATEDIFF(B.END_DATE,B.START_DATE)>89 AND C.DURATION_TYPE LIKE "90%") OR
(DATEDIFF(B.END_DATE,B.START_DATE) BETWEEN 30 AND 89 AND C.DURATION_TYPE LIKE "30%") OR
(DATEDIFF(B.END_DATE,B.START_DATE) BETWEEN 7 AND 29 AND C.DURATION_TYPE LIKE "7%")) AND A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_TYPE="트럭"
# ORDER BY HISTORY_ID;
ORDER BY FEE DESC,HISTORY_ID DESC;