-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FLAVOR,TOTAL_ORDER
FROM FIRST_HALF
GROUP BY FLAVOR) A
JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER) TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) B
ON A.FLAVOR=B.FLAVOR
ORDER BY (A.TOTAL_ORDER+B.TOTAL_ORDER) DESC
LIMIT 3;
