-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") as review_date
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID=B.MEMBER_ID
WHERE A.MEMBER_ID = (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
order by COUNT(REVIEW_ID) desc limit 1)
ORDER BY REVIEW_DATE,REVIEW_TEXT